# Generated by Django 6.0.4 on 2026-04-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='record_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('investment', 'Investment')], default='expense', max_length=15),
        ),
    ]
